#!/bin/bash
#SBATCH --time=0:00:20
#SBATCH --ntasks=28 --nodes=1 --gpus-per-node=1
#SBATCH --job-name=lab3_part3_test
#SBATCH --account=PAS2065

module load cuda

echo job started at `date`
echo on compute node `cat $PBS_NODEFILE`

cd $SLURM_SUBMIT_DIR
cd $TMPDIR

echo job started at `date` >>current.out
time $SLURM_SUBMIT_DIR/test >>current.out
echo job ended at `date` >>current.out

export SAVEDIR=${SLURM_SUBMIT_DIR}'/lab3_part3_test'
mv current.out ${SAVEDIR}