all: part1 part2 part3

part1: p1main.cu
	nvcc -o lab3p1_oadonca_donca.2 p1main.cu

part2: lab3p2.cu
	nvcc -o lab3p2_oadonca_donca.2 lab3p2.cu

part3: part3.cu
	nvcc -o lab3p3_oadonca_donca.2 part3.cu